"""Workshop master data: demand codes, labour operations, parts and campaigns.

This is the local stand-in for the OEM labour-time and EPC tables. Every rule the
estimator applies is traceable to a row here, so an advisor can see *why* a line
was added. Replace these tables with the dealer's DMS export in production.
"""

from __future__ import annotations

DEALERSHIP = {"name": "Arena Workshop, Sector 18", "lat": 28.4949, "lng": 77.0694}

LABOUR_RATE = 650  # INR per standard hour
GST = 0.18
PMS_INTERVAL_KM = 10_000
PMS_INTERVAL_DAYS = 365
WARRANTY_YEARS = 2
WARRANTY_KM = 40_000

# Demand-code taxonomy. The phrase patterns that map customer words (English, Hindi,
# Hinglish) onto these codes live with the matcher in `app.service.concerns`.
DEMAND_CODES: dict[str, dict] = {
    "PMS": {
        "label": "Periodic maintenance service",
        "system": "general",
        "cause": "Scheduled maintenance interval reached",
        "correction": "Perform periodic maintenance as per schedule",
        "labour": ["L-PMS"],
        "parts": [("P-OILF", 1), ("P-OIL", 1), ("P-AIRF", 1)],
        "warrantable": False,
        "skill": "general",
    },
    "BRK-NOISE": {
        "label": "Brake noise / judder",
        "system": "brakes",
        "cause": "Worn front brake pads, glazed or warped rotor",
        "correction": "Road test and inspect pads, rotors and calipers; confirm repair after inspection",
        "labour": ["L-BRKDIAG"],
        "parts": [("P-BRKPAD", 1)],
        "warrantable": False,
        "skill": "brakes",
    },
    "BRK-WEAK": {
        "label": "Weak / spongy brakes",
        "system": "brakes",
        "cause": "Air in brake line or low brake fluid",
        "correction": "Check hydraulic system, fluid level and leaks; confirm repair after inspection",
        "labour": ["L-BRKDIAG"],
        "parts": [("P-BRKFL", 1)],
        "warrantable": True,
        "skill": "brakes",
    },
    "AC-COOL": {
        "label": "AC not cooling",
        "system": "hvac",
        "cause": "Low refrigerant or clogged cabin filter",
        "correction": "Check AC pressure, compressor and cabin airflow; confirm repair after testing",
        "labour": ["L-ACDIAG"],
        "parts": [("P-CABINF", 1), ("P-R134A", 1)],
        "warrantable": True,
        "skill": "hvac",
    },
    "ENG-NOISE": {
        "label": "Engine abnormal noise",
        "system": "engine",
        "cause": "Loose heat shield or tappet noise",
        "correction": "Diagnose engine noise, tighten or adjust as needed",
        "labour": ["L-ENGDIAG"],
        "parts": [],
        "warrantable": True,
        "skill": "engine",
    },
    "RR-NOISE": {
        "label": "Rear-end noise while driving",
        "system": "suspension",
        # Maruti cars are front-engine / front-wheel drive: a noise from the back is
        # suspension, wheel bearing, brakes or exhaust, not the engine.
        "cause": "Worn rear shock absorber / mounting bush, rear wheel bearing or loose exhaust hanger",
        "correction": "Road test; inspect rear shock absorbers and mounts, rear wheel bearings, rear brake drums and exhaust hangers",
        "labour": ["L-REARDIAG"],
        "parts": [],
        "warrantable": True,
        "skill": "suspension",
    },
    "ENG-MIL": {
        "label": "Check-engine light on",
        "system": "engine",
        "cause": "Fault code stored in ECU",
        "correction": "Scan ECU, diagnose stored DTC, repair and clear",
        "labour": ["L-ECUSCAN"],
        "parts": [],
        "warrantable": True,
        "skill": "diagnostics",
    },
    "ENG-HEAT": {
        "label": "Engine overheating",
        "system": "engine",
        "cause": "Low coolant, stuck thermostat or radiator fan fault",
        "correction": "Pressure-test cooling system and check fan and thermostat",
        "labour": ["L-COOLDIAG"],
        "parts": [("P-COOLANT", 1)],
        "warrantable": True,
        "skill": "engine",
    },
    "ENG-OIL": {
        "label": "Oil leak / low oil pressure",
        "system": "engine",
        "cause": "Leaking gasket or seal, low oil level or clogged filter",
        "correction": "Check oil level, trace leaks and test oil pressure before repair",
        "labour": ["L-OILPRESS"],
        "parts": [("P-OILF", 1)],
        "warrantable": True,
        "skill": "engine",
    },
    "BAT-START": {
        "label": "Starting problem / weak battery",
        "system": "electrical",
        "cause": "Weak battery or loose terminal",
        "correction": "Test battery, terminals and charging system",
        "labour": ["L-BATTEST"],
        "parts": [("P-BAT", 1)],
        "warrantable": True,
        "skill": "electrical",
    },
    "SUS-NOISE": {
        "label": "Suspension noise on bumps",
        "system": "suspension",
        "cause": "Worn stabiliser link or strut mount",
        "correction": "Road test and inspect suspension joints, links and mounts",
        "labour": ["L-SUSDIAG"],
        "parts": [("P-STABLINK", 2)],
        "warrantable": True,
        "skill": "suspension",
    },
    "STR-PULL": {
        "label": "Wheel alignment & balancing / pulling",
        "system": "steering",
        "cause": "Wheel misalignment or imbalance",
        "correction": "Check tyre pressures, wheel balance and alignment before adjustment",
        "labour": ["L-STEERDIAG"],
        "parts": [("P-WEIGHTS", 1)],
        "warrantable": False,
        "skill": "general",
    },
    "BODY-DENT": {
        "label": "Body dent / scratch repair",
        "system": "body",
        "cause": "External body damage",
        "correction": "Denting and painting of affected panel",
        "labour": ["L-DENTPAINT"],
        "parts": [("P-PAINT", 1)],
        "warrantable": False,
        "skill": "body",
    },
    "CLU-HARD": {
        "label": "Clutch / gear shifting issue",
        "system": "transmission",
        "cause": "Clutch cable wear or clutch plate wear",
        "correction": "Road test and inspect clutch operation and linkage",
        "labour": ["L-CLUTCHDIAG"],
        "parts": [("P-CLUCABLE", 1)],
        "warrantable": True,
        "skill": "transmission",
    },
    "BRK-CHECK": {
        "label": "Brake inspection requested",
        "system": "brakes",
        "cause": "Customer request: pad and disc wear check",
        "correction": "Measure pad and rotor thickness, check fluid level; advise replacement only if below limit",
        "labour": ["L-BRKDIAG"],
        "parts": [],
        "warrantable": False,
        "skill": "brakes",
    },
    "ENG-PERF": {
        "label": "Low pickup / jerking",
        "system": "engine",
        "cause": "Clogged air filter, fouled spark plugs, throttle body deposits or misfire",
        "correction": "Scan ECU, road test, inspect air filter, spark plugs and throttle body",
        "labour": ["L-PERFDIAG"],
        "parts": [],
        "warrantable": True,
        "skill": "engine",
    },
    "WARN-LIGHT": {
        "label": "Dashboard warning light (system to identify)",
        "system": "diagnostics",
        "cause": "Warning lamp on cluster; system not described by the customer",
        "correction": "Identify the lamp on the cluster, scan all ECUs and diagnose the stored codes",
        "labour": ["L-ECUSCAN"],
        "parts": [],
        "warrantable": True,
        "skill": "diagnostics",
    },
    "SAF-SRS": {
        "label": "ABS / airbag warning light",
        "system": "safety",
        "cause": "ABS wheel-speed sensor, airbag clock spring or connector fault stored",
        "correction": "Scan ABS and SRS modules, inspect sensors and connectors; safety item, do not release untested",
        "labour": ["L-SRSDIAG"],
        "parts": [],
        "warrantable": True,
        "skill": "diagnostics",
    },
    "ELEC-CHG": {
        "label": "Battery / charging warning light",
        "system": "electrical",
        "cause": "Alternator output low, slipping drive belt or battery terminal fault",
        "correction": "Test alternator output, drive belt and battery terminals",
        "labour": ["L-BATTEST"],
        "parts": [],
        "warrantable": True,
        "skill": "electrical",
    },
    "ELEC-ACC": {
        "label": "Electrical accessory not working",
        "system": "electrical",
        "cause": "Blown fuse, faulty relay or switch, or wiring connector fault",
        "correction": "Check fuse, relay, switch and connector for the named accessory; repair after test",
        "labour": ["L-ELECDIAG"],
        "parts": [],
        "warrantable": True,
        "skill": "electrical",
    },
    "EXH-SMOKE": {
        "label": "Exhaust smoke / exhaust noise",
        "system": "engine",
        "cause": "Rich mixture (black), oil burning (blue) or coolant entry (white); or exhaust leak",
        "correction": "Note smoke colour, scan ECU, check exhaust joints; compression test if oil burning",
        "labour": ["L-EXHDIAG"],
        "parts": [],
        "warrantable": True,
        "skill": "engine",
    },
    "FUEL-EFF": {
        "label": "Low fuel economy",
        "system": "engine",
        "cause": "Low tyre pressure, clogged air filter, dragging brakes or driving pattern",
        "correction": "Check tyre pressures, air filter, brake drag and ECU data; advise on driving pattern",
        "labour": ["L-PERFDIAG"],
        "parts": [],
        "warrantable": False,
        "skill": "engine",
    },
    "TYRE": {
        "label": "Tyre wear / puncture",
        "system": "steering",
        "cause": "Puncture, low pressure or uneven wear from misalignment",
        "correction": "Inspect tyres, repair puncture, check pressures and wear pattern; align if uneven",
        "labour": ["L-TYRE"],
        "parts": [],
        "warrantable": False,
        "skill": "general",
    },
    "BODY-RATTLE": {
        "label": "Cabin / door rattle",
        "system": "body",
        "cause": "Loose trim clip, door striker or dashboard fastener",
        "correction": "Road test to locate the rattle; secure trim, striker or fastener",
        "labour": ["L-RATTLE"],
        "parts": [],
        "warrantable": True,
        "skill": "general",
    },
    "WASH": {
        "label": "Washing and interior cleaning",
        "system": "general",
        "cause": "Customer request",
        "correction": "Exterior wash and interior vacuum",
        "labour": ["L-WASH"],
        "parts": [],
        "warrantable": False,
        "skill": "general",
    },
}

LABOUR_OPS: dict[str, dict] = {
    "L-PMS": {"desc": "Periodic maintenance (standard)", "hours": 1.5},
    "L-BRKDIAG": {"desc": "Brake system inspection and road test", "hours": 0.5},
    "L-BRKPAD": {"desc": "Front brake pad replacement", "hours": 0.8},
    "L-BRKBLEED": {"desc": "Brake bleeding and fluid top-up", "hours": 0.6},
    "L-ACGAS": {"desc": "AC diagnosis and gas recharge", "hours": 1.0},
    "L-ACDIAG": {"desc": "AC system diagnosis", "hours": 0.6},
    "L-ENGDIAG": {"desc": "Engine noise diagnosis", "hours": 0.7},
    "L-ECUSCAN": {"desc": "ECU scan and DTC diagnosis", "hours": 0.5},
    "L-COOLDIAG": {"desc": "Cooling system pressure test and diagnosis", "hours": 0.8},
    "L-OILPRESS": {"desc": "Oil and fuel pressure diagnosis", "hours": 0.9},
    "L-BATTEST": {"desc": "Battery and charging system test", "hours": 0.3},
    "L-REARDIAG": {"desc": "Rear noise road test and underbody inspection", "hours": 0.8},
    "L-SUSLINK": {"desc": "Stabiliser link replacement (pair)", "hours": 0.9},
    "L-SUSDIAG": {"desc": "Suspension inspection and road test", "hours": 0.6},
    "L-ALIGN": {"desc": "Wheel alignment and balancing", "hours": 0.8},
    "L-STEERDIAG": {"desc": "Steering and wheel inspection", "hours": 0.6},
    "L-DENTPAINT": {"desc": "Denting and painting (per panel)", "hours": 4.0},
    "L-CLUADJ": {"desc": "Clutch adjustment / cable replacement", "hours": 0.7},
    "L-CLUTCHDIAG": {"desc": "Clutch and gearshift diagnosis", "hours": 0.6},
    "L-WASH": {"desc": "Wash and vacuum", "hours": 0.5},
    "L-PERFDIAG": {"desc": "Performance road test and ECU data check", "hours": 0.8},
    "L-SRSDIAG": {"desc": "ABS / SRS module scan and sensor check", "hours": 0.6},
    "L-ELECDIAG": {"desc": "Electrical circuit test (fuse, relay, switch)", "hours": 0.5},
    "L-EXHDIAG": {"desc": "Exhaust smoke and leak diagnosis", "hours": 0.7},
    "L-TYRE": {"desc": "Tyre inspection, puncture repair and pressure check", "hours": 0.4},
    "L-RATTLE": {"desc": "Rattle location road test and trim fixing", "hours": 0.6},
}

# part_no -> name, unit price, compatible alternative part numbers
PARTS: dict[str, dict] = {
    "P-OILF": {"name": "Oil filter", "price": 290, "alt": []},
    "P-OIL": {"name": "Engine oil 3.5L 0W-16", "price": 1650, "alt": ["P-OIL-ALT"]},
    "P-OIL-ALT": {"name": "Engine oil 3.5L 5W-30", "price": 1450, "alt": []},
    "P-AIRF": {"name": "Air filter element", "price": 420, "alt": []},
    "P-BRKPAD": {"name": "Front brake pad set", "price": 2350, "alt": ["P-BRKPAD-ALT"]},
    "P-BRKPAD-ALT": {"name": "Front brake pad set (economy)", "price": 1790, "alt": []},
    "P-BRKFL": {"name": "Brake fluid DOT4 500ml", "price": 380, "alt": []},
    "P-CABINF": {"name": "Cabin air filter", "price": 520, "alt": []},
    "P-R134A": {"name": "Refrigerant R134a charge", "price": 1200, "alt": []},
    "P-COOLANT": {"name": "Engine coolant 2L", "price": 640, "alt": []},
    "P-BAT": {"name": "Battery 35Ah", "price": 4800, "alt": []},
    "P-STABLINK": {"name": "Stabiliser link", "price": 890, "alt": []},
    "P-WEIGHTS": {"name": "Wheel balancing weights", "price": 150, "alt": []},
    "P-PAINT": {"name": "Paint material (per panel)", "price": 2600, "alt": []},
    "P-CLUCABLE": {"name": "Clutch cable", "price": 760, "alt": []},
}

STOCK_LOCATIONS = {
    "own": {"label": "Own stock", "eta_hours": 0},
    "dealer_b": {"label": "Dealer B (network transfer)", "eta_hours": 4},
    "warehouse": {"label": "Regional warehouse (order)", "eta_hours": 24},
}

# Service campaigns / recalls, matched by model and VIN serial range.
CAMPAIGNS = [
    {
        "code": "CMP-2611",
        "title": "Fuel pump relay inspection",
        "models": ["Baleno", "Swift"],
        "vin_serial_max": 450_000,
        "labour": "L-ECUSCAN",
    },
    {
        "code": "CMP-2604",
        "title": "Rear seat-belt buckle check",
        "models": ["Ertiga", "XL6"],
        "vin_serial_max": 999_999,
        "labour": "L-BATTEST",
    },
]

BAY_TYPES = {
    "general": ["general", "brakes", "suspension", "steering", "transmission", "electrical", "engine", "diagnostics", "hvac"],
    "express": ["general"],
    "body": ["body"],
    "wash": ["general"],
}
